import { ApolloProvider } from '@parkspace/network/src/config/apollo'
import '@parkspace/ui/src/app/globals.css'
import { Container } from '@parkspace/ui/src/components/atoms/Container'
import { SessionProvider } from '@parkspace/ui/src/components/molecules/SessionProvider'
import { ToastContainer } from '@parkspace/ui/src/components/molecules/Toast'
import { Header } from '@parkspace/ui/src/components/organisms/Header'
import { MenuItem } from '@parkspace/util/types'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import 'react-toastify/dist/ReactToastify.css'

const monserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Parkspace | Admin',
  description: 'Generated by create next app',
}

const MENUITEMS: MenuItem[] = [
  { label: 'Garages', href: '/' },
  { label: 'Admins', href: '/manageAdmins' },
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${monserrat.className} bg-gray-25`}>
        <SessionProvider>
          <ApolloProvider>
            <Header type="admin" menuItems={MENUITEMS} />
            <Container>{children}</Container>
          </ApolloProvider>
        </SessionProvider>
        <ToastContainer />
      </body>
    </html>
  )
}
