import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import '@parkspace/ui/src/app/globals.css'
import { MenuItem } from '@parkspace/util/types'
import { ApolloProvider } from '@parkspace/network/src/config/apollo'
import { SessionProvider } from '@parkspace/ui/src/components/molecules/SessionProvider'
import { ToastContainer } from '@parkspace/ui/src/components/molecules/Toast'
import { Container } from '@parkspace/ui/src/components/atoms/Container'
import { Header } from '@parkspace/ui/src/components/organisms/Header'
import 'react-toastify/dist/ReactToastify.css'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Parkspace | Valet',
  description: 'Generated by create next app',
}

const MENUITEMS: MenuItem[] = [{ label: 'My Trips', href: '/my-trips' }]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} bg-gray-25`}>
        <SessionProvider>
          <ApolloProvider>
            <Header type="valet" menuItems={MENUITEMS} />
            <Container>{children}</Container>
          </ApolloProvider>
        </SessionProvider>
        <ToastContainer />
      </body>
    </html>
  )
}
